### ISSUE TITLE
python3 为什么会报错SyntaxError: Non-ASCII character '\xe6' in file

### ISSUE THREAD

**Issue by SaltNego** [honghaier-game/TKinterDesigner#33]
错误信息输出窗口.
Traceback (most recent call last):
  File "Project4.py", line 4, in <module>
    import Project4_cmd
  File "D:\Download\IDM\Compressed\Compressed\TKinterDesigner-v1.6.2-win64\Project4\Project4_cmd.py", line 9, in <module>
    import Fun
  File "D:\Download\IDM\Compressed\Compressed\TKinterDesigner-v1.6.2-win64\Project4\Fun.py", line 1
SyntaxError: Non-ASCII character '\xe6' in file D:\Download\IDM\Compressed\Compressed\TKinterDesigner-v1.6.2-win64\Project4\Fun.py on line 1, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

**Comment by SaltNego** [comment]
版本1.6.2
